- custom_components/vigieau/__init__.py
It will ease debugging
Change-Id: Icaaf9fbe560d637f91c185dd8910d7fc5b3586cc
> 🚧 Support injection of location

- custom_components/vigieau/__init__.py
Fixes #3
Change-Id: Id604c1787f45ac57bfdb55f26f99e8690166b287
> ✨ Support zone without any restriction

- custom_components/vigieau/__init__.py
- custom_components/vigieau/const.py
This will make sure we control the number of sensors even if there is no categorisation of data in the api
Change-Id: Id96069bf2b1773da360d34e093ac4dff4a91d07c
> ✨ Stop unbounded growth of sensors

- custom_components/vigieau/const.py
Fixes #10
Change-Id: I696c0ac5950d63218a039b8ef5e8f47c79d0a082
> ✨ Increase restriction coverage

- custom_components/vigieau/const.py
Thanks @WarC0zes for the suggestion!
Fix #14
Change-Id: Iff13e211dd4aa3ec4a071e94adabbe9609efcd9e
> 🎨 Add icons for roofs and water ponds

- README.md
- custom_components/vigieau/__init__.py
- custom_components/vigieau/const.py
Some coordinates are not known by the governement geocoding api.
This patch creates a possible bypass for users living in such areas.
It will fix #9 and serve as a very first step for #11 implementation
Fix #9
> ✨ Allow to bypass geocoding

- custom_components/vigieau/__init__.py
I should learn to test code before shipping!
Fix #18
Change-Id: If7b1eea206cfd1c87bea1b201c6f896702b176dd
> 🐛 Correct geocoding parameter

- custom_components/vigieau/const.py
It seems common enough to deserve its own sensor
Fix #20
> ✨ Add support for voirie/trottoirs sensor

- custom_components/vigieau/__init__.py
> 🐛 Handle alerte renforcée

- custom_components/vigieau/__init__.py
Since yesterday 3:34PM, vigieau api returns "Erreur" instead of providing the niveauRestriction key Now we fallback with the erreur message
> 🐛 Deal with API soft errors

- custom_components/vigieau/__init__.py
Previous patch worked only in case the API returned an error 🤦️
Change-Id: Id8e7a2e3623fc126bb1ba88049a8a7f4af539313
> 🐛 Fixup to handle case where API does *not* return an error

- custom_components/vigieau/const.py
Fix #27
Change-Id: If32799faebcc9de9dd2d536e92b46f453bba5fab
> ✨ Support restriction on "Vidange des plans d'eau"

- custom_components/vigieau/__init__.py
In a previous patch, we merged several "restrictions" into a unified sensor per logical usage. It led to expose time restriction per restriction, in attributes.
That made exploitation of time-based restriction harder to exploit because users had to parse complex keys like "Arrosage des jardins potagers (heureDebut)".
We simplify this for the majority of case where a single restriction is used for a specific sensor.
This change won't chnage anything for the complex case but is breaking for the (hopefully most common) case: we loose the "xxx (heureDebut)" attribute in favor of "heureDebut".
Change-Id: If177ce5d8ab34ec82ba3fb208c6b5f744cfd0506
> ✨ Expose simple heureDebug/heureFin attributes

- custom_components/vigieau/const.py
It just appeared in Eure-et-Loire
Change-Id: I878df34e5bec500a29da189434f372540881957c
> ✨ Support "Manoeuvre de vannes des seuils et barrages" usage

- custom_components/vigieau/__init__.py
- custom_components/vigieau/const.py
Hat off to @sebcaps for proposing this change in #30
Change-Id: If33b99be1ac28af2e85fabf16aa9ec560a08695c
> 🚧 Simplify usage matching with sensors

- custom_components/vigieau/__init__.py
- custom_components/vigieau/config_flow.py
> 🐛 Allow config migration to version from version 2

- custom_components/vigieau/const.py
Also add one new sensor for "Navigation fluviale" since it did not fit in any category
Fix #41
> ✨ Add more sensor matchers

- .github/workflows/test.yml
- .gitignore
- custom_components/vigieau/api.py
- custom_components/vigieau/const.py
- custom_components/vigieau/scripts/full_usage_list.json
- custom_components/vigieau/scripts/generate_list.py
- custom_components/vigieau/tests/test_regexp.py
- requirements.txt
- requirements_tests.txt
We download the list of all restrictions from all cities in France. A test is added to ensure we support all restrictions
Partially implements #44
> Add support for all existing restrictions

- custom_components/vigieau/__init__.py
This state seems quite rare
Fix #47
> 🐛 Support "réduction de prélevement" state

- custom_components/vigieau/const.py
- custom_components/vigieau/scripts/full_usage_list.json
> Update known/handled restrictions

- custom_components/vigieau/__init__.py
- custom_components/vigieau/api.py
- custom_components/vigieau/const.py
Vigieau API was updated last month and got out of beta.
This patch tries to restore features.
partially fix #58
> Restore compatibility with vigieau API

- custom_components/vigieau/__init__.py
New status does not have the accent
Fix #61
> Support alerte_renforcee

- custom_components/vigieau/const.py
- custom_components/vigieau/scripts/full_usage_list.json
based on dump of all existing restrictions from 2024-07-29
> Update supported restrictions

- custom_components/vigieau/__init__.py
> ✨ Support sensibilisation level

- custom_components/vigieau/__init__.py
> Interpret sensibilisation level

- custom_components/vigieau/__init__.py
- custom_components/vigieau/api.py
- custom_components/vigieau/config_flow.py
- custom_components/vigieau/const.py
> 🚧 Prepare customization of zone type

- custom_components/vigieau/__init__.py
- custom_components/vigieau/config_flow.py
- custom_components/vigieau/const.py
- custom_components/vigieau/translations/fr.json
This allows to select type of water (surface, below surface, tap water) to which restrictions apply
Fix #73
> ✨ Support zone type selection

- README.md
- custom_components/vigieau/__init__.py
- custom_components/vigieau/api.py
- custom_components/vigieau/config_flow.py
- custom_components/vigieau/const.py
- custom_components/vigieau/scripts/generate_list.py
- custom_components/vigieau/sensor.py
Un peu de nettoyage de code avec quelques bonnes pratiques et puis quelques corrections de mots
Je n'ai pas testé si le code fonctionne correctement, je manque d'expérience pour tester mes modifs en local
> Clean code

- custom_components/vigieau/__init__.py
- custom_components/vigieau/api.py
This is a recurring question from users, let's make it more explicit.
Fix #82
> ✨ Rename default level

- custom_components/vigieau/__init__.py
- custom_components/vigieau/api.py
- custom_components/vigieau/sensor.py
For people building automations
> ✨ Expose stable/numerical alert level entity

- .github/workflows/hacs.yml
- .github/workflows/hassfest.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- hacs.json
Pour permettre aux futures "release" du produit, et qu'elles puissent s'afficher avec le bon numéro de version dans HACS et dans l'intégration.
Je me suis appuyé sur plusieurs "custom component" ( [spook](https://github.com/frenck/spook), [alarmo](https://github.com/nielsfaber/alarmo)  )
> Update GitHub workflow

- custom_components/vigieau/api.py
- custom_components/vigieau/const.py
- url has changed
- returned data is an array of a 0,1 element instead of a hash
Fix #78
> ✨ Support latest version of vigieau api

- custom_components/vigieau/const.py
- custom_components/vigieau/scripts/full_usage_list.json
- custom_components/vigieau/scripts/generate_list.py
and improve the refresh script to be append-only
Fix #92
> ♻️ Refresh usage list

- custom_components/vigieau/const.py
- custom_components/vigieau/scripts/full_usage_list.json
> Update usage list

- custom_components/vigieau/__init__.py
> Handle reduction recommendation
